apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-vol-pv   
spec:
  capacity:
    storage: 100Gi     
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: glusterfs-cluster 
    path: /k8s-vol1 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
