apiVersion: "v1"
kind: "PersistentVolume"
metadata:
name: "k8s-vol1"
spec:
capacity:
storage: "8Gi"
accessModes:
- "ReadWriteMany"
glusterfs:
endpoints: "glusterfs-cluster"
path: "k8s-vol1"
readOnly: false
persistentVolumeReclaimPolicy: "Recycle"
